name: sip_fork
version: 1.0.0
description: A simple SIP client based on the forked dart-sip-ua dependency.
homepage: https://github.com/MARK-46/sip-ua-fork
environment:
  sdk: ^3.8.1
  flutter: ">=2.0.0"
dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  flutter_webrtc: ^1.1.0
  intl: ^0.18.0
  parser_error: ^0.2.0
  path: ^1.6.4
  recase: ^4.0.0
  sdp_transform: ^0.3.2
  uuid: ^3.0.2
  web_socket_client: ^0.1.2
  logger: 
